apiVersion: v1
kind: Service
metadata:
  name: audio-sketchbook
  namespace: audio-sketchbook
spec:
  type: NodePort
  selector:
    app: audio-sketchbook
  ports:
    - port: 8765
      targetPort: 8765
      nodePort: 30087
